USE MovieDB;

CREATE TABLE Genre
(
	GenreID INT AUTO_INCREMENT NOT null,
	GenreName NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_Genre PRIMARY KEY (GenreID)
);

CREATE TABLE UserType
(
	UserTypeID INT AUTO_INCREMENT NOT NULL,
	UserTypeName VARCHAR(20) NOT NULL,
	CONSTRAINT PK_UserType PRIMARY KEY (UserTypeID)
);

CREATE TABLE `User`
(
	UserID INT auto_increment NOT NULL,
	FirstName NVARCHAR(150) NOT NULL,
	LastName NVARCHAR(150) NOT NULL,
	Username NVARCHAR(20) NOT NULL,
	PASSWORD NVARCHAR(40) NOT NULL,
	Gender VARCHAR(6) NULL,
	UserTypeID INT NOT NULL,
	CONSTRAINT PK_User PRIMARY KEY (UserID),
	CONSTRAINT FK_User_UserType
		FOREIGN KEY (UserTypeID)
		REFERENCES UserType(UserTypeID)
);

CREATE TABLE Movie
(
	MovieID INT AUTO_INCREMENT NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	Overview NVARCHAR(1024) NOT NULL,
	Genre NVARCHAR(30) NOT NULL,
	LANGUAGE NVARCHAR(30) NOT NULL,
	Duration INT NOT NULL,
	Rating DECIMAL(3,1) NULL,
	PosterPath VARCHAR(100) NULL,
	CONSTRAINT PK_Movie PRIMARY KEY (MovieID)
);

CREATE TABLE Watchlist
(
	WatchlistID INT AUTO_INCREMENT NOT NULL,
	UserID INT NOT NULL,
	DateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_Watchlist PRIMARY KEY (WatchlistID)
);

CREATE TABLE WatchlistItem
(
	WatchlistItemID INT AUTO_INCREMENT NOT NULL,
	WatchlistID INT NOT NULL,
	MovieID INT NOT NULL,
	CONSTRAINT PK_WatchlistItem PRIMARY KEY(WatchlistItemID),
	CONSTRAINT FK_WatchlistItem_Watchlist
		FOREIGN KEY (WatchlistID)
		REFERENCES Watchlist(WatchlistID),
	CONSTRAINT FK_WatchlistIteem_Movie
		FOREIGN KEY (MovieID)
		REFERENCES Movie(MovieID)
);
